services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - chat-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - AUTH_PORT
      - JWT_SECRET
      - MONGO_URI
    networks:
      - chat-network

  chat-backend:
    build: ./chat-backend
    container_name: chat-backend
    environment:
      - JWT_SECRET
      - BACKEND_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST

    ports:
      - "3000:3000"
    volumes:
      - ./chat-backend:/app
      - /app/node_modules
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge